// deno-lint-ignore-file ban-unused-ignore no-explicit-any no-empty-interface
///////////////////////////////////
// !!! DO NOT EDIT THIS FILE !!! //
///////////////////////////////////

import { SlackAPIResponse } from "../response.ts";
export type AdminInviteRequestsDeniedListResponse = SlackAPIResponse & {
  denied_requests?: string[];
  error?: string;
  needed?: string;
  ok: boolean;
  provided?: string;
};
