// deno-lint-ignore-file ban-unused-ignore no-explicit-any no-empty-interface
///////////////////////////////////
// !!! DO NOT EDIT THIS FILE !!! //
///////////////////////////////////

import type { SlackAPIResponse } from "../response.ts";
export type MigrationExchangeResponse = SlackAPIResponse & {
  enterprise_id?: string;
  error?: string;
  invalid_user_ids?: string[];
  needed?: string;
  ok: boolean;
  provided?: string;
  team_id?: string;
  user_id_map?: UseridMap;
  warning?: string;
};

export interface UseridMap {}
